<?php

use BloomNetwork\BloomNet;
use Carbon\Carbon;

class CheckAvailabilityTest extends \PHPUnit\Framework\TestCase
{
    protected BloomNet $bloom;

    public function setUp(): void
    {
        $this->bloom = new BloomNet('N872', 'qa', 'N8720000');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGettingAvailabilityByDateForLocationTest()
    {
        $response = $this->bloom->isAvaliableForDeliveryOnDateAndZipCode(Carbon::today()->addWeeks(2), '60632');

        $this->assertTrue($response);
    }
}