<?php

use BloomNetwork\BloomNet;

class GetMemberDirectoryTest extends \PHPUnit\Framework\TestCase
{
    protected BloomNet $bloom;

    public function setUp(): void
    {
        $this->bloom = new BloomNet('N872', 'qa', 'N8720000');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGettingMemberDirectory()
    {
        $response = $this->bloom->getMemberDirectory();

        file_put_contents('directory.xml', $response->getBody());
    }
}
