<?php

use BloomNetwork\BloomNet;
use PHPUnit\Framework\TestCase;

class SendOrderTest extends TestCase
{
    protected BloomNet $bloom;

    public function setUp(): void
    {
        $this->bloom = new BloomNet();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSendingAnOrder()
    {
        $item = $this->bloom->sendOrder('tests/stubs/sendOrderMessage.xml');

        dd((string)$item->getBody());
    }
}