<?php

use BloomNetwork\BloomNet;
use BloomNetwork\Models\Items\DeliveryDetails;
use Carbon\Carbon;
use PHPUnit\Framework\TestCase;

class SendOrderTest extends TestCase
{
    protected BloomNet $bloom;

    public function setUp(): void
    {
        $this->bloom = new BloomNet('N872', 'qa', 'N8720000', false);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSendingAnOrder()
    {
        $item = $this->bloom->sendOrder(
            new \BloomNetwork\Models\Items\Recipient(
                'John',
                'Doe',
                '123 Main St',
                'Anytown',
                'NY',
                '12345',
                'US',
                '555-555-5555',
                null,
                'Apt 2'
            ),
            [
                new \BloomNetwork\Models\Items\OrderProductionInfo(
                    1,
                    45,
                    'Test Product'
                ),
            ],
            new DeliveryDetails(
                Carbon::now(),
                '',
            ),
            (string)rand(5000, 9900),
            45,
            '', // custom message?
        );

        dd((string)$item->getBody());
    }
}
